### PR TITLE
Add optimization parameters

### PR DESCRIPTION
**Pull request by arntanguy**
This PR adds optimization parameters, as supported by Eigen 3.2.0  (Ubuntu 14.04)

Warning: There seems to be a change of interface for Eigen 3.2.9  (optimization parameters accessed through setters instead of directly by a public variable).

I'm not sure which version of Eigen is intended to be supported?

### CODE REVIEW

**Comment by bchretien** [comment]
:+1: Thanks!

If the API changes, both should APIs be supported. I couldn't find this change though in the repo. Do you have a link by any chance?

The tests currently fail because of an (unrelated) error in the DLL export macro. `ROBOPTIM_DLLEXPORT` should be `ROBOPTIM_CORE_PLUGIN_EIGEN_DLLEXPORT`, with `#include "roboptim/core/plugin/eigen/config.hh"`. Could you had a commit fixing this in this PR as well?

**Comment by arntanguy** [comment]
Just pushed the DLLEXPORT changes.

As for Eigen, I investigated a bit:
- The API change occurs between 
[3.1](https://bitbucket.org/eigen/eigen/src/2524f6185981c6ec1782aeea7f3e2c56211cac13/unsupported/Eigen/src/NonLinearOptimization/LevenbergMarquardt.h?at=3.1&fileviewer=file-view-default) and [3.2](https://bitbucket.org/eigen/eigen/src/1e7d97fea51d0ac8bf038fe4eab15bbbbd20b9e6/unsupported/Eigen/src/LevenbergMarquardt/LevenbergMarquardt.h?at=3.2&fileviewer=file-view-default): LevenbergMarquardt is moved into its own directory, and the API changes.

- Ubuntu 14.04 package is supposed to be based on Eigen 3.2.0-8, but as far as I can tell, it is in fact
based on Eigen 3.1 (I checked the code within the package, and it's consistent with 3.1)

- The listed required dependency for oboptim-core-plugin-eigen is eigen 3.2.0, so in theory we should aim for supporting this. However, this would be quite problematic on Ubuntu trusty.

What do you reckon?

**Comment by bchretien** [comment]
Apparently both versions are still available, in the 3.2.9 release we have:

- `unsupported/Eigen/src/LevenbergMarquardt/LevenbergMarquardt.h`
- `unsupported/Eigen/src/NonLinearOptimization/LevenbergMarquardt.h`

For backwards compatibility, if the former header remains available, I guess we should keep on using it for now. If the only change is just about setting the parameters, we could imagine adding a preprocessor check for the Eigen version, and then relying on one API or the other based on that. It's probably not that important, especially if both implementations have the same performance at runtime.

If this all sounds good for you, I can merge your PR now that tests are passing.

**Comment by arntanguy** [comment]
Sounds good to me, let's keep using the old header for now.

**Comment by bchretien** [comment]
LGTM then, thanks!

**Pull request merged**
